# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d52227cad9c0e489924fff057579f3b3d5b021b5b7feb345b86deb57f16589787d005e0464f6b7163944d096b135a46e5a9a14c16544be1181f263c432b7c38

test:
  secret_key_base: 335ac9729022cf42d03aaff13f4cba836737cc20f04e4ac6c609989ccf5c20e8f8383b410d2cae7a1850459808704da04ea69992c49d4b4988f1d751644c3baf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
